apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-workflows
spec:
  gateways:
    - runhub
  hosts:
    - argo-workflows.runhub.localhost
  http:
    - route:
        - destination:
            host: argo-workflows-server.argo.svc.cluster.local
            port:
              number: 2746
