apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-dev-runhub
product: k3d
k3d:
  v1alpha5Simple:
    metadata:
      name: "k3d-version-{{ .Values.k3dVersion }}"
    image: rancher/k3s:v1.29.3-k3s1
    volumes:
      - volume: "{{ .Values.runhubAbsoluteDir }}:/runhub"
        nodeFilters:
          - server:*
          - agent:*
    ports:
      - port: 8080:80
        nodeFilters:
          - loadbalancer
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:0
