apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-runhub
image: rancher/k3s:v1.29.1-k3s1
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
