#{{ define "runhub.app.argo-cd" }}
metadata:
  name: argo-cd
  labels:
    app: argo-cd
spec:
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.7.18
      chart: argo-cd
      helm:
        releaseName: argocd
        values: |
          configs:
            cm:
              admin.enabled: false
              application.resourceTrackingMethod: annotation
              resource.customizations: |
                argoproj.io/Application:
                  health.lua: |
                    hs = {}
                    hs.status = "Progressing"
                    hs.message = ""
                    if obj.status ~= nil then
                      if obj.status.health ~= nil then
                        if obj.status.health.status ~= nil then
                          hs.status = obj.status.health.status
                        end
                        if obj.status.health.message ~= nil then
                          hs.message = obj.status.health.message
                        end
                      end
                    end
                    return hs
                serving.knative.dev/Configuration:
                  health.lua: |
                    local hs = {}
                    hs.status = "Progressing"
                    hs.message = ""
                    if obj.status ~= nil then
                      if obj.status.conditions ~= nil then
                        for i, condition in pairs(obj.status.conditions) do
                          if condition.type == "Ready" and condition.status == "True" then
                            hs.status = "Healthy"
                            break
                          end
                        end
                      end
                    end
                    return hs
              users.anonymous.enabled: true
            params:
              applicationsetcontroller.enable.progressive.syncs: true
              server.insecure: true
            rbac:
              policy.default: role:admin
          repoServer:
            volumeMounts:
              - mountPath: /runhub
                name: runhub
                readOnly: true
            volumes:
              - name: runhub
                hostPath:
                  path: /runhub
                  type: Directory
          server:
            service:
              servicePortHttpsName: grpc
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      path: charts/namespace
      helm:
        releaseName: argocd
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      path: charts/argo-cd
      helm:
        releaseName: argocd
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 0
#{{ end }}
