#{{ define "runhub.app.knative-operator" }}
metadata:
  name: knative-operator
  labels:
    app: knative-operator
spec:
  sources:
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      path: kustomizations/knative-operator
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      path: charts/namespace
  destination:
    name: in-cluster
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 0
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - clusterrole-aggregation-controller
#{{ end }}
