#{{ define "runhub.app.knative-operator" }}
metadata:
  name: knative-operator
  labels:
    app: knative-operator
spec:
  source:
    repoURL: "{{ .Values.runhub.repository }}"
    targetRevision: "{{ .Values.runhub.revision }}"
    path: kustomizations/knative-operator
  destination:
    name: in-cluster
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 0
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - clusterrole-aggregation-controller
#{{ end }}
