#{{ define "runhub.app.knative-serving" }}
metadata:
  name: knative-serving
  labels:
    app: knative-serving
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: "{{ .Values.runhub.repository }}"
    targetRevision: "{{ .Values.runhub.revision }}"
    path: charts/knative-serving
  destination:
    name: in-cluster
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 0
#{{ end }}
