#{{ define "runhub.app.runhub-istio" }}
metadata:
  name: runhub-istio
  labels:
    app: runhub-istio
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: "{{ .Values.runhub.repository }}"
    targetRevision: "{{ .Values.runhub.revision }}"
    path: charts/runhub-istio
  destination:
    name: in-cluster
    namespace: "{{ .Release.Namespace }}"
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 0
#{{ end }}
