#{{ define "runhub.app.runhub-network" }}
metadata:
  name: runhub-network
  labels:
    app: runhub-network
spec:
  source:
    repoURL: "{{ .Values.runhub.repository }}"
    targetRevision: "{{ .Values.runhub.revision }}"
    path: charts/runhub-network
  destination:
    name: in-cluster
    namespace: "{{ .Release.Namespace }}"
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 0
    syncOptions:
      - CreateNamespace=true
#{{ end }}
