apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: runhub
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.1.1
      chart: argo-cd
      helm:
        releaseName: argocd
        valuesObject:
          configs:
            cm:
              admin.enabled: false
              application.resourceTrackingMethod: annotation
              resource.customizations: |
                argoproj.io/Application:
                  health.lua: |
                    {{ .Files.Get "health-checks/app.lua" | indent 20 | trim }}
                operator.knative.dev/KnativeServing:
                  health.lua: |
                    {{ .Files.Get "health-checks/ready.lua" | indent 20 | trim }}
                serving.knative.dev/Configuration:
                  health.lua: |
                    {{ .Files.Get "health-checks/ready.lua" | indent 20 | trim }}
              resource.customizations.ignoreResourceUpdates.all: |
                jsonPointers:
                  - /status
              resource.ignoreResourceUpdatesEnabled: true
              users.anonymous.enabled: true
            params:
              server.insecure: true
            rbac:
              policy.default: role:admin
          repoServer:
            volumeMounts:
              - mountPath: /runhub
                name: runhub
                readOnly: true
            volumes:
              - name: runhub
                hostPath:
                  path: /runhub
                  type: Directory
          server:
            service:
              servicePortHttpsName: grpc
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      path: charts/namespace
      helm:
        releaseName: argocd
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      path: charts/argo-cd
      helm:
        releaseName: argocd
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    retry: {}
