apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: runhub
  source:
    repoURL: "{{ .Values.runhub.repository }}"
    targetRevision: "{{ .Values.runhub.revision }}"
    path: kustomizations/knative-operator
  destination:
    name: in-cluster
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
    retry: {}
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - clusterrole-aggregation-controller
