#{{ if .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runhub-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: runhub
  source:
    repoURL: "{{ .Values.runhub.repository }}"
    targetRevision: "{{ .Values.runhub.revision }}"
    path: charts/runhub-apps
    helm:
      valuesObject: #{{ toYaml .Values | nindent 8 }}
  destination:
    name: in-cluster
    namespace: "{{ .Release.Namespace }}"
  syncPolicy:
    automated:
      prune: true
    retry: {}
#{{ end }}
