apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-cd
  namespace: "{{ .Release.Namespace }}"
spec:
  gateways:
    - runhub
  hosts:
    - "runhub-argo-cd.{{ .Values.runhub.domain }}"
  http:
    - match:
        - headers:
            content-type:
              exact: application/grpc
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 443
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
