apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: runhub
  namespace: "{{ .Release.Namespace }}"
spec:
  gateways:
    - runhub
  hosts:
    - "runhub.{{ .Values.runhub.domain }}"
  http:
    - redirect:
        authority: "runhub-argo-cd.{{ .Values.runhub.domain }}:8080"
        redirectCode: 307
