#{{ range $serviceName, $service := .Values.services }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ $serviceName }}"
  namespace: "{{ $.Release.Namespace }}"
spec:
  gateways:
    - runhub/runhub
  hosts:
    - "{{ $.Values.app.name }}-{{ $serviceName  }}.localhost"
  http:
    - rewrite:
        authority: "{{ $serviceName  }}.{{ $.Release.Namespace }}.svc.cluster.local"
      route:
        - destination:
            host: "{{ $serviceName  }}.{{ $.Release.Namespace }}.svc.cluster.local"
            port:
              number: 80
#{{ end }}
