apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: "{{ .Release.Namespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos: []
  destinations: []
  namespaceResourceWhitelist: []
  clusterResourceWhitelist: []
