apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: "{{ .Values.service.name }}"
spec:
  template:
    metadata:
      name: "{{ .Values.service.name }}-{{ .Values.app.revision }}"
    spec:
      containers:
        - image: "{{ .Values.service.image }}"
