apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: routes-hook
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - configurations
    verbs:
      - list
  - apiGroups:
      - serving.knative.dev
    resources:
      - routes
    verbs:
      - patch
