apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ .Release.Namespace }}"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - stage: deployments
          - stage: routes
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - deployments
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - routes
  template:
    metadata:
      name: "{{ .Release.Namespace }}-{{ `{{ .stage }}` }}"
      labels:
        stage: "{{ `{{ .stage }}` }}"
    spec:
      project: "{{ .Release.Namespace }}"
      source:
        repoURL: "{{ .Values.runhub.repository }}"
        targetRevision: "{{ .Values.runhub.revision }}"
        path: "charts/runhub-app-{{ `{{ .stage }}` }}"
      destination:
        name: in-cluster
        namespace: "{{ .Release.Namespace }}"
      syncPolicy:
        automated:
          prune: true
        retry:
          limit: 0
  templatePatch: |
    spec:
      source:
        helm:
          values: |{{ toYaml .Values | nindent 12 }}
