#{{ range $serviceName, $service := .Values.services }}
---
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: "{{ $serviceName }}"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - image: "{{ $service.image }}"
#{{ end }}
