#{{ range $serviceName, $service := .Values.services }}
---
apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: "{{ $serviceName }}"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  traffic:
    - configurationName: "{{ $serviceName }}"
      percent: 100
#{{ end }}
