apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: runhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceNamespaces:
    - runhub
  sourceRepos:
    - "{{ .Values.runhub.repository }}"
    - https://argoproj.github.io/argo-helm
    - https://istio-release.storage.googleapis.com/charts
  destinations:
    - namespace: "*"
      name: in-cluster
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
