apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runhub
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          -  #{{ include "runhub.app.argo-cd" . | indent 12 }}
          -  #{{ include "runhub.app.istio-base" . | indent 12 }}
          -  #{{ include "runhub.app.istiod" . | indent 12 }}
          -  #{{ include "runhub.app.istio-ingressgateway" . | indent 12 }}
          -  #{{ include "runhub.app.runhub-network" . | indent 12 }}
          -  #{{ include "runhub.app.knative-operator" . | indent 12 }}
          -  #{{ include "runhub.app.knative-serving" . | indent 12 }}
          #{{ if .Values.apps }}
          -  #{{ include "runhub.app.apps" . | indent 12 }}
          #{{ end }}
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - argo-cd
        - matchExpressions:
            - key: app
              operator: In
              values:
                - istio-base
        - matchExpressions:
            - key: app
              operator: In
              values:
                - istiod
        - matchExpressions:
            - key: app
              operator: In
              values:
                - istio-ingressgateway
        - matchExpressions:
            - key: app
              operator: In
              values:
                - runhub-network
        - matchExpressions:
            - key: app
              operator: In
              values:
                - knative-operator
        - matchExpressions:
            - key: app
              operator: In
              values:
                - knative-serving
        #{{ if .Values.apps }}
        - matchExpressions:
            - key: app
              operator: In
              values:
                - apps
        #{{ end }}
  template:
    metadata: {}
    spec:
      project: runhub
      destination: {}
  templatePatch: |
    {{ `{{ toYaml . | indent 4 }}` }}
