apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runhub
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: argo-cd
            repoURL: https://argoproj.github.io/argo-helm
            targetRevision: 6.7.6
            chart: argo-cd
            valuesObject:
              configs:
                cm:
                  admin.enabled: false
                  resource.customizations: |
                    argoproj.io/ApplicationSet:
                      health.lua: |
                        local hs = {}
                        hs.status = "Progressing"
                        hs.message = ""

                        if obj.status ~= nil then
                          if obj.status.conditions ~= nil then
                            for i, condition in pairs(obj.status.conditions) do
                              if condition.type == "ErrorOccurred" and condition.status == "True" then
                                hs.status = "Degraded"
                                hs.message = condition.message
                                return hs
                              end
                              if condition.type == "ResourcesUpToDate" and condition.status == "True" then
                                if obj.spec.strategy ~= nil and obj.spec.strategy.type == "RollingSync" then
                                  if obj.status.applicationStatus ~= nil then
                                    for i, applicationStatus in pairs(obj.status.applicationStatus) do
                                      if applicationStatus.status ~= "Healthy" then
                                        hs.message = applicationStatus.application .. ": " .. applicationStatus.message
                                        return hs
                                      end
                                    end
                                    hs.status = "Healthy"
                                    hs.message = condition.message
                                    return hs
                                  end
                                else
                                  hs.status = "Healthy"
                                  hs.message = condition.message
                                  return hs
                                end
                              end
                            end
                          end
                        end

                        return hs
                  users.anonymous.enabled: true
                params:
                  applicationsetcontroller.enable.progressive.syncs: true
                  server.insecure: true
                rbac:
                  policy.default: role:admin
              repoServer:
                volumeMounts:
                  - mountPath: /runhub
                    name: runhub
                    readOnly: true
                volumes:
                  - name: runhub
                    hostPath:
                      path: /runhub
                      type: Directory
              server:
                service:
                  servicePortHttpsName: grpc
            namespace: argocd
          - name: istio
            repoURL: "{{ .Values.runhub.repository }}"
            targetRevision: "{{ .Values.runhub.revision }}"
            path: charts/istio
            namespace: "{{ .Release.Namespace }}"
          - name: knative-operator
            repoURL: "{{ .Values.runhub.repository }}"
            targetRevision: "{{ .Values.runhub.revision }}"
            path: kustomizations/knative-operator
            namespace: knative-operator
            ignoreDifferences:
              - group: "*"
                kind: "*"
                managedFieldsManagers:
                  - clusterrole-aggregation-controller
          - name: runhub-network
            repoURL: "{{ .Values.runhub.repository }}"
            targetRevision: "{{ .Values.runhub.revision }}"
            path: charts/runhub-network
            namespace: "{{ .Release.Namespace }}"
          - name: knative-serving
            repoURL: "{{ .Values.runhub.repository }}"
            targetRevision: "{{ .Values.runhub.revision }}"
            path: charts/knative-serving
            namespace: knative-serving
          #{{ if .Values.apps }}
          - name: apps
            repoURL: "{{ .Values.runhub.repository }}"
            targetRevision: "{{ .Values.runhub.revision }}"
            path: charts/apps
            valuesObject: #{{ toYaml .Values | nindent 14 }}
            namespace: "{{ .Release.Namespace }}"
          #{{ end }}
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - argo-cd
        - matchExpressions:
            - key: app
              operator: In
              values:
                - istio
        - matchExpressions:
            - key: app
              operator: In
              values:
                - knative-operator
                - runhub-network
        - matchExpressions:
            - key: app
              operator: In
              values:
                - knative-serving
        #{{ if .Values.apps }}
        - matchExpressions:
            - key: app
              operator: In
              values:
                - apps
        #{{ end }}
  template:
    metadata:
      name: "{{ `{{ .name }}` }}"
      labels:
        app: "{{ `{{ .name }}` }}"
    spec:
      project: runhub
      source:
        repoURL: "{{ `{{ .repoURL }}` }}"
        targetRevision: "{{ `{{ .targetRevision }}` }}"
      destination:
        name: in-cluster
        namespace: "{{ `{{ .namespace }}` }}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        {{ `{{- if hasKey . "chart" }}` }}
        chart: "{{ `{{ .chart }}` }}"
        {{ `{{- else }}` }}
        path: "{{ `{{ .path }}` }}"
        {{ `{{- end }}` }}
        {{ `{{- if hasKey . "valuesObject" }}` }}
        helm:
          values: |
            {{ `{{ toYaml .valuesObject | indent 8 | trim }}` }}
        {{ `{{- end }}` }}
    {{ `{{- if hasKey . "ignoreDifferences" }}` }}
      ignoreDifferences: {{ `{{ toYaml .ignoreDifferences | nindent 8 }}` }}
    {{ `{{- end }}` }}
