apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: runhub
  namespace: argocd
spec:
  sourceRepos:
    - "{{ .Values.repository }}"
    - https://argoproj.github.io/argo-helm
    - https://istio-release.storage.googleapis.com/charts
  destinations:
    - name: in-cluster
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
