apiVersion: v1
kind: Secret
metadata:
  name: repos
  annotations:
    build.shipwright.io/referenced.secret: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: rh-gh-{{ lower .Values.reposOwner }}-[a-z0-9-]+-pr-[0-9]+
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.reposToken }}
  username: {{ .Values.reposUsername }}
