apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rh-gh-{{ lower .Values.reposOwner }}-prs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: runhub
  source:
    repoURL: {{ .Values.runhubRepoURL }}
    targetRevision: {{ .Values.runhubRevision }}
    path: manifests/prs
    helm:
      parameters:
        - name: runhubRepoURL
          value: {{ .Values.runhubRepoURL }}
        - name: runhubRevision
          value: {{ .Values.runhubRevision }}
        - name: reposOwner
          value: {{ .Values.reposOwner }}
      releaseName: prs
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
      - PrunePropagationPolicy=background
      - FailOnSharedResource=true
