apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipwright-builds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: runhub
  source:
    repoURL: {{ .Values.runhubRepoURL }}
    targetRevision: {{ .Values.runhubRevision }}
    path: manifests/shipwright-builds
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
      - PrunePropagationPolicy=background
      - FailOnSharedResource=true
