apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: runhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - {{ .Values.runhubRepoURL }}
  destinations:
    - name: in-cluster
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
