apiVersion: v1
kind: Secret
metadata:
  name: repos
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/{{ .Values.reposOwner }}
  password: {{ .Values.reposToken }}
  username: {{ .Values.reposUsername }}
