apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          #{{ range $appName, $app := .Values.apps }}
          - name: "runhub-app-{{ $appName }}"
            valuesObject:
              app: #{{ toYaml $app | nindent 16 }}
                name: "{{ $appName }}"
              runhub: #{{ toYaml $.Values.runhub | nindent 16 }}
          #{{ end }}
  template:
    metadata:
      name: "{{ `{{ .name }}` }}"
    spec:
      project: "{{ `{{ .name }}` }}"
      destination:
        name: in-cluster
        namespace: "{{ `{{ .name }}` }}"
      syncPolicy:
        automated:
          prune: true
        retry:
          limit: 0
  templatePatch: |
    spec:
      sources:
        - repoURL: "{{ .Values.runhub.repository }}"
          targetRevision: "{{ .Values.runhub.revision }}"
          path: charts/app
          helm:
            valueFiles:
              - $appRepository/runhub-app.yaml
            values: |{{ `{{ toYaml .valuesObject | nindent 10 }}` }}
        - repoURL: "{{ `{{ .valuesObject.app.repository }}` }}"
          targetRevision: "{{ `{{ .valuesObject.app.revision }}` }}"
          ref: appRepository
        - repoURL: "{{ .Values.runhub.repository }}"
          targetRevision: "{{ .Values.runhub.revision }}"
          path: charts/namespace
