#{{ range $appName, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "runhub-app-{{ $appName }}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "{{ $.Values.runhub.repository }}"
    - "{{ $app.repository }}"
  destinations:
    - namespace: "runhub-app-{{ $appName }}"
      name: in-cluster
    - namespace: argocd
      name: in-cluster
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
#{{ end }}
