apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          #{{ range $appName, $app := .Values.apps }}
          - app: #{{ toYaml $app | nindent 14 }}
              name: "{{ $appName }}"
            runhub: #{{ toYaml $.Values.runhub | nindent 14 }}
          #{{ end }}
  template:
    metadata:
      name: "runhub-app-{{ `{{ .app.name }}` }}"
    spec:
      project: "runhub-app-{{ `{{ .app.name }}` }}"
      destination:
        name: in-cluster
        namespace: "runhub-app-{{ `{{ .app.name }}` }}"
      syncPolicy:
        automated:
          prune: true
  templatePatch: |
    spec:
      sources:
        - repoURL: "{{ .Values.runhub.repository }}"
          targetRevision: "{{ .Values.runhub.revision }}"
          path: charts/app
          helm:
            valueFiles:
              - $appRepository/runhub-app.yaml
            values: |{{ `{{ toYaml . | nindent 10 }}` }}
        - repoURL: "{{ `{{ .app.repository }}` }}"
          targetRevision: "{{ `{{ .app.revision }}` }}"
          ref: appRepository
