apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: runhub-operator
  namespace: argocd
spec:
  sourceRepos:
    - "{{ .Values.repository }}"
  destinations:
    - name: in-cluster
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
