apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runhub-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        #{{ if hasKey .Values "dev" }}
        repoURL: "{{ .Values.dev.repository }}"
        revision: "{{ .Values.dev.revision }}"
        #{{ else }}
        repoURL: "{{ .Values.infra.repository }}"
        revision: "{{ .Values.infra.revision }}"
        #{{ end }}
        files:
          - path: runhub-infra.yaml
  template:
    metadata:
      name: runhub
    spec:
      project: runhub-operator
      destination:
        name: in-cluster
        namespace: "{{ .Release.Namespace }}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      sources:
        {{- if hasKey .Values "dev" }}
        - repoURL: "{{ .Values.dev.repository }}"
          targetRevision: "{{ .Values.dev.revision }}"
        {{- else }}
        - repoURL: "{{ `{{ .runhub.repository }}` }}"
          targetRevision: "{{ `{{ .runhub.revision }}` }}"
        {{- end }}
          path: charts/runhub
          helm:
            valueFiles:
              - $infraRepository/runhub-infra.yaml
            {{- if hasKey .Values "dev" }}
            parameters:
              - name: runhub.repository
                value: "{{ .Values.dev.repository }}"
              - name: runhub.revision
                value: "{{ .Values.dev.revision }}"
              {{ `{{- if hasKey . "apps" }}` }}
              {{ `{{- range $appName, $app := .apps }}` }}
              - name: "apps.{{ `{{ $appName }}` }}.repository"
                value: "{{ .Values.dev.repository }}"
              - name: "apps.{{ `{{ $appName }}` }}.revision"
                value: "{{ .Values.dev.revision }}"
              {{ `{{- end }}` }}
              {{ `{{- end }}` }}
            {{- end }}
        {{- if hasKey .Values "dev" }}
        - repoURL: "{{ .Values.dev.repository }}"
          targetRevision: "{{ .Values.dev.revision }}"
        {{- else }}
        - repoURL: "{{ .Values.infra.repository }}"
          targetRevision: "{{ .Values.infra.revision }}"
        {{- end }}
          ref: infraRepository
