apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: runhub-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    #{{ if get .Values "dev" }}
    - "{{ .Values.dev.repository }}"
    #{{ else }}
    - "{{ .Values.runhub.repository }}"
    - "{{ .Values.infra.repository }}"
    #{{ end }}
  destinations:
    - namespace: "*"
      name: in-cluster
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
