apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: runhub
  namespace: argocd
spec:
  sourceNamespaces:
    - argocd
  sourceRepos:
    - "{{ .Values.repoURL }}"
    - https://argoproj.github.io/argo-helm
  destinations:
    - name: in-cluster
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
