apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runhub
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: runhub-operator
  sources:
    #{{ if get .Values "dev" }}
    - repoURL: "{{ .Values.dev.repository }}"
      targetRevision: "{{ .Values.dev.revision }}"
    #{{ else }}
    - repoURL: "{{ .Values.runhub.repository }}"
      targetRevision: "{{ .Values.runhub.revision }}"
      #{{ end }}
      path: charts/runhub
      helm:
        valueFiles:
          - $infraRepository/runhub-infra.yaml
        #{{ if get .Values "dev" }}
        parameters:
          - name: runhub.repository
            value: "{{ .Values.dev.repository }}"
          - name: runhub.revision
            value: "{{ .Values.dev.revision }}"
          #{{ range $appName, $app := .Values.apps }}
          - name: "apps.{{ $appName }}.repository"
            value: "{{ $.Values.dev.repository }}"
          - name: "apps.{{ $appName }}.revision"
            value: "{{ $.Values.dev.revision }}"
          #{{ end }}
        #{{ end }}
    #{{ if get .Values "dev" }}
    - repoURL: "{{ .Values.dev.repository }}"
      targetRevision: "{{ .Values.dev.revision }}"
    #{{ else }}
    - repoURL: "{{ .Values.infra.repository }}"
      targetRevision: "{{ .Values.infra.revision }}"
      #{{ end }}
      ref: infraRepository
  destination:
    name: in-cluster
    namespace: "{{ .Release.Namespace }}"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
