#{{ range $appName, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "rh-{{ $appName }}"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  sourceRepos:
    - "{{ $.Values.runhub.repository }}"
    - "{{ $app.repository }}"
  destinations:
    - namespace: "rh-{{ $appName }}"
      name: in-cluster
    - namespace: argocd
      name: in-cluster
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
#{{ end }}
