#{{ range $appName, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "rh-{{ $appName }}"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "rh-{{ $appName }}"
  sources:
    - repoURL: "{{ $.Values.runhub.repository }}"
      targetRevision: "{{ $.Values.runhub.revision }}"
      path: charts/runhub-app
      helm:
        valueFiles:
          - $appRepository/runhub-app.yaml
        values: |
          app: {{ toYaml $app | nindent 12 }}
            name: "{{ $appName }}"
          runhub: {{ toYaml $.Values.runhub | nindent 12 }}
    - repoURL: "{{ $app.repository}}"
      targetRevision: "{{ $app.revision }}"
      ref: appRepository
  destination:
    name: in-cluster
    namespace: "rh-{{ $appName }}"
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 0
#{{ end }}
