#{{ range $appName, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "rh-{{ $appName }}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "rh-{{ $appName }}"
  sources:
    - repoURL: "{{ $.Values.runhub.repository }}"
      targetRevision: "{{ $.Values.runhub.revision }}"
      path: charts/runhub-app
      helm:
        valueFiles:
          - $appRepository/runhub-app.yaml
        valuesObject:
          app: #{{ toYaml $app | nindent 12 }}
            name: "{{ $appName }}"
          runhub: #{{ toYaml $.Values.runhub | nindent 12 }}
    - repoURL: "{{ $app.repository}}"
      targetRevision: "{{ $app.revision }}"
      ref: appRepository
  destination:
    name: in-cluster
    namespace: "rh-{{ $appName }}"
  syncPolicy:
    automated:
      prune: true
    retry: {}
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: serving.knative.dev
      kind: Route
      jsonPointers:
        - /spec/traffic
#{{ end }}
