apiVersion: v1
kind: ConfigMap
metadata:
  generateName: wait-for-crds-
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
