apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rh-gh-{{ lower .Values.reposOwner }}-prs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - {{ .Values.runhubRepoURL }}
    - https://github.com/{{ lower .Values.reposOwner }}/*.git
  destinations:
    - name: in-cluster
      namespace: rh-gh-{{ lower .Values.reposOwner }}-*-pr-*
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
