apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rh-gh-{{ lower .Values.reposOwner }}-prs
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - scmProvider:
              cloneProtocol: https
              filters:
                - pathsExist:
                    - runhub.yaml
              github:
                organization: {{ .Values.reposOwner }}
                allBranches: true
                tokenRef:
                  secretName: repos
                  key: password
          - pullRequest:
              filters:
                - branchMatch: '{{"{{"}} .branch }}'
              github:
                owner: {{ .Values.reposOwner }}
                repo: '{{"{{"}} .repository }}'
                tokenRef:
                  secretName: repos
                  key: password
  goTemplate: true
  template:
    metadata:
      name: rh-gh-{{ lower .Values.reposOwner }}-{{"{{"}} lower .repository }}-pr-{{"{{"}} .number }}
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: rh-gh-{{ lower .Values.reposOwner }}-prs
      sources:
        - repoURL: {{ .Values.runhubRepoURL }}
          targetRevision: {{ .Values.runhubRevision }}
          path: manifests/app
          helm:
            parameters:
              - name: repoURL
                value: '{{"{{"}} .url }}'
              - name: revision
                value: '{{"{{"}} .head_sha }}'
              - name: containerRegistryURL
                value: {{ .Values.containerRegistryURL }}
            releaseName: app
            valueFiles:
              - $repo/runhub.yaml
        - repoURL: '{{"{{"}} .url }}'
          targetRevision: '{{"{{"}} .head_sha }}'
          ref: repo
      destination:
        name: in-cluster
        namespace: rh-gh-{{ lower .Values.reposOwner }}-{{"{{"}} lower .repository }}-pr-{{"{{"}} .number }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - PruneLast=true
          - PrunePropagationPolicy=background
          - FailOnSharedResource=true
      ignoreDifferences:
        - group: ""
          kind: Secret
          jsonPointers:
            - /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflected-version
            - /data
