apiVersion: v1
kind: Secret
metadata:
  name: repos
  annotations:
    build.shipwright.io/referenced.secret: "true"
    reflector.v1.k8s.emberstack.com/reflects: "runhub/repos"
    reflector.v1.k8s.emberstack.com/reflected-version: ""
type: kubernetes.io/basic-auth
stringData:
  password: <not-yet-reflected>
  username: <not-yet-reflected>
